DATA_LIST:
  - "macroprops30minData4UT-1.csv"
  - "macroprops30minData4UT-2.csv"
  - "macroprops30minData4UT-3.csv"
  - "macroprops30minData4UT-4.csv"
  - "macroprops30minData4UT-5.csv"
  - "macroprops30minData4UT-6.csv"