DATA_LIST:
- ["crossing_90_a_01.pkl", 2083]
- ["crossing_90_a_02.pkl", 1635]
- ["crossing_90_a_03.pkl", 1117]
- ["crossing_90_a_04.pkl", 1298]
- ["crossing_90_a_05.pkl", 1083]
- ["crossing_90_a_06.pkl", 580]
- ["crossing_90_a_07.pkl", 1232]
- ["crossing_90_a_08.pkl", 884]
- ["crossing_90_a_09.pkl", 1434]
- ["crossing_90_a_10.pkl", 1161]
- ["crossing_90_b_02.pkl", 2580]
- ["crossing_90_b_03.pkl", 1448]
- ["crossing_90_b_04.pkl", 1336]
- ["crossing_90_b_05.pkl", 1185]
- ["crossing_90_b_06.pkl", 1220]
- ["crossing_90_b_07.pkl", 1188]