DATA_FS:
  RAW_DATA_DIR: '/datasets/HERMES-CR-120/rawData/'
  AGG_DATA_DIR: '/datasets/HERMES-CR-120/aggData/'
  PICKLE_DIR: '/datasets/HERMES-CR-120/processed/'
  OUTPUT_DIR : "output_hermes_cr_120"
  SAVE_DIR: "saved_models/hermes_cr_120/"
  USE_PICKLE: False
MACROPROPS:
  # Grid size
  ROWS: 28
  COLS: 24
  # Grid resolution
  DX: 0.5
  DY: 0.5
  LU:
    - -5
    - 8
  # EPSILON value to avoid division by cero
  EPS: 0.000001
  OVERLAP: False
  WINDOWSIZE: 7
  THETA: 0
  TIME_RES: 0.25
DATASET:
  NAME: "HERMES-CR-120"
  PAST_LEN: 5
  FUTURE_LEN: 3
  TRAIN_FILE_COUNT: 18
  VAL_FILE_COUNT: 2
  TEST_FILE_COUNT: 2
  BATCH_SIZE: 64
  params:
    shuffle: True
    num_workers: 6
    drop_last: True
  DATASET_TYPE: 'BySplitRatio'    # Available options: ByFilenames|BySplitRatio|ByFilenames4Test
  VELOCITY_NORM: False
MODEL:
  NAME: "ARCH-{}_HERMESCR_TE{}_PL{}_FL{}_CE{}_VN{}.pth"
  NSAMPLES: 1280      # Define number of predicted samples (64 BS * 20 rep, default values)
  NSAMPLES4PLOTS: 20  # Define number of predicted samples to plot static and dynamic seqs
  DDPM:
    SAMPLER: "DDPM"
    TIMESTEPS: 1000     # Define canonical number of diffusion timesteps
    SCALE: 0.5          # Define scale for betas in model
    DDIM_DIVIDER: 90    # Define number of timesteps to divide by
    GUIDANCE: 'sparsity' # Possible values: None, sparsity, mass_preservation
    MODEL_SAMPLES: 7
    TRAIN:
      EPOCHS: 200
      SOLVER:
        LR: 0.00005
        WEIGHT_DECAY: 0.003
        BETAS:
          - 0.5
          - 0.999
    UNET:
      CONDITION: "Past"
      CONDITION_HANDLING: "embed"
      NUM_RES_BLOCKS: 1
      BASE_CH: 32  # 64, 128, 256, 512
      BASE_CH_MULT: [1, 2, 4] # 32, 16, 8, 4
      APPLY_ATTENTION: [False, False, True, False]
      DROPOUT_RATE: 0.1
      TIME_EMB_MULT: 4 # 128
    VIT:
      TMP_VAR: "Placeholder"
  FLOW_MATCHING:
    TMP_VAR: "Placeholder"
  CONVGRU:
    TEACHER_FORCING: True
    ENC_HIDDEN_CH: [16, 64, 64, 96, 96, 96]
    FORC_HIDDEN_CH: [96, 96, 96, 96, 96, 64, 16]
    ENC_KERNELS: [3, 3, 3, 3, 3, 3]
    FORC_KERNELS: [3, 4, 3, 4, 3, 3, 3]
    TRAIN:
      EPOCHS: 100
      SOLVER:
        LR: 0.0005
        WEIGHT_DECAY: 0.0003
        BETAS:
          - 0.7
          - 0.999
METRICS:
  PRED_MPROPS_FACTOR: [1, 1, 1]
  MPROPS_COUNT: 3    # Metrics consider rho, vx, vy predictions only
  MOTION_FEATURE:
    f: 1    # Number of frames of each volume
    k: 4    # Spatial dimensions of each volume, valid for ATC grid
    s: 1
    GAMMA: 2.0 # Exponent of the power function for 1D-histogram
TRAIN:
  INITIAL_LR: 0.0005
  EPOCHS: 200
  SOLVER:
    LR: 0.00005
    WEIGHT_DECAY: 0.003
    BETAS:
      - 0.5
      - 0.999