DATA_AGGREGATION:
  RAW_DATA_DIR: 'datasets/HERMES-CR-120-OBS/rawData/'
  AGG_DATA_DIR: 'datasets/HERMES-CR-120-OBS/aggData/'
PICKLE:
  PICKLE_DIR: '/datasets/HERMES-CR-120-OBS/processed'
  USE_PICKLE: False
MACROPROPS:
  # Grid size
  ROWS: 28
  COLS: 24
  # Grid resolution
  DX: 0.5
  DY: 0.5
  LU:
    - -5
    - 8
  # EPSILON value to avoid division by cero
  EPS: 0.000001
  OVERLAP: False
  WINDOWSIZE: 1
  THETA: 0
  TIME_RES: 0.25
  MPROPS_COUNT: 3
DATASET:
  NAME: "HERMES-CR-120-OBS"
  PAST_LEN: 5
  FUTURE_LEN: 3
  TRAIN_FILE_COUNT: 18
  VAL_FILE_COUNT: 2
  TEST_FILE_COUNT: 2
  BATCH_SIZE: 64
  params:
    shuffle: True
    num_workers: 6
  DATASET_TYPE: 'BySplitRatio'    # Available options: ByFilenames|BySplitRatio|ByFilenames4Test
MODEL:
  CONDITION: "Past"
  CONDITION_HANDLING: "embed"
  NUM_RES_BLOCKS: 1
  BASE_CH: 32  # 64, 128, 256, 512
  BASE_CH_MULT: [1, 2, 4] # 32, 16, 8, 4
  APPLY_ATTENTION: [False, False, True, False]
  DROPOUT_RATE: 0.1
  TIME_EMB_MULT: 4 # 128
  SAVE_DIR: "saved_models/"
  OUTPUT_DIR : "output_hermes_cr_120_obs"
  MODEL_NAME: "UNet_Mprops4D_SizeS_HERMESCR_OBS_E{}_LR{}_TFC{}_PL{}_FL{}.pth"
  RETRAIN: False
  MIN_RHO_4_PRED: 20
DIFFUSION:
  SAMPLER: "DDPM"
  TIMESTEPS: 1000     # Define canonical number of diffusion timesteps
  SCALE: 0.5          # Define scale for betas in model
  DDIM_DIVIDER: 90    # Define number of timesteps to divide by
  NSAMPLES: 1280      # Define number of predicted samples (64 BS * 20 rep, default values)
  NSAMPLES4PLOTS: 20  # Define number of predicted samples to plot static and dynamic seqs
  PRED_MPROPS_FACTOR: [1, 10, 10, 10] # QA: not sure if we still needs this
  GUIDANCE: 'sparsity' # Possible values: None, sparsity, mass_preservation
METRICS:
  MOTION_FEATURE:
    f: 1    # Number of frames of each volume
    k: 4    # Spatial dimensions of each volume, valid for ATC grid
    s: 1
    GAMMA: 2.0 # Exponent of the power function for 1D-histogram
TRAIN:
  INITIAL_LR: 0.0005
  EPOCHS: 250
  SOLVER:
    LR: 0.00005
    WEIGHT_DECAY: 0.003
    BETAS:
      - 0.5
      - 0.999