DATA_LIST:
- ["crossing_90_c_01.pkl", 2529]
- ["crossing_90_c_02.pkl", 1326]
- ["crossing_90_c_03.pkl", 1100]
- ["crossing_90_c_04.pkl", 1237]
- ["crossing_90_c_05.pkl", 1452]
- ["crossing_90_c_06.pkl", 1316]
- ["crossing_90_c_07.pkl", 1166]
- ["crossing_90_c_08.pkl", 1098]