DATA_LIST:
  - "crossing_120_a_01.txt"
  - "crossing_120_a_02.txt"
  - "crossing_120_a_03.txt"
  - "crossing_120_a_04.txt"
  - "crossing_120_a_05.txt"
  - "crossing_120_a_06.txt"
  - "crossing_120_a_07.txt"
  - "crossing_120_b_01.txt"
  - "crossing_120_b_02.txt"