DATA_LIST:
- ["crossing_90_a_01.pkl", 2075]
- ["crossing_90_a_02.pkl", 1627]
- ["crossing_90_a_03.pkl", 1109]
- ["crossing_90_a_04.pkl", 1290]
- ["crossing_90_a_05.pkl", 1075]
- ["crossing_90_a_06.pkl", 572]
- ["crossing_90_a_07.pkl", 1224]
- ["crossing_90_a_08.pkl", 876]
- ["crossing_90_a_09.pkl", 1426]
- ["crossing_90_a_10.pkl", 1153]
- ["crossing_90_b_02.pkl", 2572]
- ["crossing_90_b_03.pkl", 1440]
- ["crossing_90_b_04.pkl", 1328]
- ["crossing_90_b_05.pkl", 1177]
- ["crossing_90_b_06.pkl", 1212]
- ["crossing_90_b_07.pkl", 1180]