DATA_LIST:
- ["macroprops30minData4UT-1.pkl", 51]
- ["macroprops30minData4UT-2.pkl", 51]
- ["macroprops30minData4UT-3.pkl", 51]
- ["macroprops30minData4UT-4.pkl", 51]
- ["macroprops30minData4UT-5.pkl", 51]
- ["macroprops30minData4UT-6.pkl", 51]