DATA_FS:
  RAW_DATA_DIR: 'datasets/ATC/rawData/'
  AGG_DATA_DIR: 'datasets/ATC/aggData/'
  PICKLE_DIR: 'datasets/ATC/pickle/'
  OUTPUT_DIR : "output_atc"
  SAVE_DIR: "saved_models/atc/"
  USE_PICKLE: False
MACROPROPS:
  # Grid size
  ROWS: 12
  COLS: 36
  # Grid resolution
  DX: 1.0
  DY: 1.0
  # Section of ATC mall: central square [-25,10], east corridor [10,-20], init mall [12, -15]
  LU:
    - 38.2789
    - -15.8076
  # EPSILON value to avoid division by cero
  EPS: 0.000001
  OVERLAP: True
  WINDOWSIZE: 1
  THETA: 2.5647
  TIME_RES: 0.5
DATASET:
  NAME: "ATC4TEST"
  PAST_LEN: 5
  FUTURE_LEN: 3 # predicted sequence
  TRAIN_FILE_COUNT: 3
  VAL_FILE_COUNT: 2
  TEST_FILE_COUNT: 1
  BATCH_SIZE: 32
  params:
    shuffle: True
    num_workers: 6
    drop_last: True
  DATASET_TYPE: 'ByFilenames'    # Available options: ByFilenames|BySplitRatio|ByFilenames4Test
  VELOCITY_NORM: True
MODEL:
  NAME: "ARCH-{}_ATC4TEST_TE{}_PL{}_FL{}_CE{}_VN{}.pth"
  NSAMPLES: 1280      # Define number of predicted samples (64 BS * 20 rep, default values)
  NSAMPLES4PLOTS: 20  # Define number of predicted samples to plot static and dynamic seqs
  DDPM:
    SAMPLER: "DDPM"
    TIMESTEPS: 1000     # Define canonical number of diffusion timesteps
    SCALE: 0.5          # Define scale for betas in model
    DDIM_DIVIDER: 90    # Define number of timesteps to divide by
    GUIDANCE: 'sparsity' # Possible values: None, sparsity, mass_preservation
    MODEL_SAMPLES: 7
    UNET:
      CONDITION: "Past"
      CONDITION_HANDLING: "embed"
      NUM_RES_BLOCKS: 1
      BASE_CH: 32  # 64, 128, 256, 512
      BASE_CH_MULT: [1, 2, 4] # 32, 16, 8, 4
      APPLY_ATTENTION: [False, False, True, False]
      DROPOUT_RATE: 0.1
      TIME_EMB_MULT: 4 # 128
    VIT:
      TMP_VAR: "Placeholder"
  FLOW_MATCHING:
    TMP_VAR: "Placeholder"
  CONVGRU:
    TEACHER_FORCING: False
    ENC_HIDDEN_CH: [16, 64, 64, 96, 96, 96]
    FORC_HIDDEN_CH: [96, 96, 96, 96, 96, 64, 16]
    ENC_KERNELS: [3, 3, 3, 3, 3, 3]
    FORC_KERNELS: [3, 4, 3, 4, 3, 3, 3]
METRICS:
  PRED_MPROPS_FACTOR: [1, 10, 10]
  MPROPS_COUNT: 3    # Metrics consider rho, vx, vy predictions only
  MOTION_FEATURE:
    f: 1    # Number of frames of each volume
    k: 4    # Spatial dimensions of each volume, valid for ATC grid
    s: 1
    GAMMA: 2.0 # Exponent of the power function for 1D-histogram
TRAIN:
  INITIAL_LR: 0.0005
  EPOCHS: 10
  SOLVER:
    LR: 0.00005
    WEIGHT_DECAY: 0.003
    BETAS:
      - 0.5
      - 0.999